// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.11
// 	protoc        v6.33.4
// source: proto/sidequest/v1/items.proto

package sidequestv1

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	emptypb "google.golang.org/protobuf/types/known/emptypb"
	structpb "google.golang.org/protobuf/types/known/structpb"
	timestamppb "google.golang.org/protobuf/types/known/timestamppb"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type EventType int32

const (
	EventType_EVENT_TYPE_UNSPECIFIED EventType = 0
	EventType_EVENT_TYPE_CREATED     EventType = 1
	EventType_EVENT_TYPE_UPDATED     EventType = 2
	EventType_EVENT_TYPE_DELETED     EventType = 3
)

// Enum value maps for EventType.
var (
	EventType_name = map[int32]string{
		0: "EVENT_TYPE_UNSPECIFIED",
		1: "EVENT_TYPE_CREATED",
		2: "EVENT_TYPE_UPDATED",
		3: "EVENT_TYPE_DELETED",
	}
	EventType_value = map[string]int32{
		"EVENT_TYPE_UNSPECIFIED": 0,
		"EVENT_TYPE_CREATED":     1,
		"EVENT_TYPE_UPDATED":     2,
		"EVENT_TYPE_DELETED":     3,
	}
)

func (x EventType) Enum() *EventType {
	p := new(EventType)
	*p = x
	return p
}

func (x EventType) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (EventType) Descriptor() protoreflect.EnumDescriptor {
	return file_proto_sidequest_v1_items_proto_enumTypes[0].Descriptor()
}

func (EventType) Type() protoreflect.EnumType {
	return &file_proto_sidequest_v1_items_proto_enumTypes[0]
}

func (x EventType) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use EventType.Descriptor instead.
func (EventType) EnumDescriptor() ([]byte, []int) {
	return file_proto_sidequest_v1_items_proto_rawDescGZIP(), []int{0}
}

type Item struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Id            string                 `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
	Name          string                 `protobuf:"bytes,2,opt,name=name,proto3" json:"name,omitempty"`
	Labels        map[string]string      `protobuf:"bytes,3,rep,name=labels,proto3" json:"labels,omitempty" protobuf_key:"bytes,1,opt,name=key" protobuf_val:"bytes,2,opt,name=value"`
	Data          *structpb.Struct       `protobuf:"bytes,4,opt,name=data,proto3" json:"data,omitempty"`
	CreatedAt     *timestamppb.Timestamp `protobuf:"bytes,5,opt,name=created_at,json=createdAt,proto3" json:"created_at,omitempty"`
	UpdatedAt     *timestamppb.Timestamp `protobuf:"bytes,6,opt,name=updated_at,json=updatedAt,proto3" json:"updated_at,omitempty"`
	Version       int32                  `protobuf:"varint,7,opt,name=version,proto3" json:"version,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Item) Reset() {
	*x = Item{}
	mi := &file_proto_sidequest_v1_items_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Item) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Item) ProtoMessage() {}

func (x *Item) ProtoReflect() protoreflect.Message {
	mi := &file_proto_sidequest_v1_items_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Item.ProtoReflect.Descriptor instead.
func (*Item) Descriptor() ([]byte, []int) {
	return file_proto_sidequest_v1_items_proto_rawDescGZIP(), []int{0}
}

func (x *Item) GetId() string {
	if x != nil {
		return x.Id
	}
	return ""
}

func (x *Item) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

func (x *Item) GetLabels() map[string]string {
	if x != nil {
		return x.Labels
	}
	return nil
}

func (x *Item) GetData() *structpb.Struct {
	if x != nil {
		return x.Data
	}
	return nil
}

func (x *Item) GetCreatedAt() *timestamppb.Timestamp {
	if x != nil {
		return x.CreatedAt
	}
	return nil
}

func (x *Item) GetUpdatedAt() *timestamppb.Timestamp {
	if x != nil {
		return x.UpdatedAt
	}
	return nil
}

func (x *Item) GetVersion() int32 {
	if x != nil {
		return x.Version
	}
	return 0
}

type GetItemRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Id            string                 `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetItemRequest) Reset() {
	*x = GetItemRequest{}
	mi := &file_proto_sidequest_v1_items_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetItemRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetItemRequest) ProtoMessage() {}

func (x *GetItemRequest) ProtoReflect() protoreflect.Message {
	mi := &file_proto_sidequest_v1_items_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetItemRequest.ProtoReflect.Descriptor instead.
func (*GetItemRequest) Descriptor() ([]byte, []int) {
	return file_proto_sidequest_v1_items_proto_rawDescGZIP(), []int{1}
}

func (x *GetItemRequest) GetId() string {
	if x != nil {
		return x.Id
	}
	return ""
}

type ListItemsRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Page          int32                  `protobuf:"varint,1,opt,name=page,proto3" json:"page,omitempty"`
	Limit         int32                  `protobuf:"varint,2,opt,name=limit,proto3" json:"limit,omitempty"`
	Sort          string                 `protobuf:"bytes,3,opt,name=sort,proto3" json:"sort,omitempty"`
	Labels        map[string]string      `protobuf:"bytes,4,rep,name=labels,proto3" json:"labels,omitempty" protobuf_key:"bytes,1,opt,name=key" protobuf_val:"bytes,2,opt,name=value"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ListItemsRequest) Reset() {
	*x = ListItemsRequest{}
	mi := &file_proto_sidequest_v1_items_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ListItemsRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ListItemsRequest) ProtoMessage() {}

func (x *ListItemsRequest) ProtoReflect() protoreflect.Message {
	mi := &file_proto_sidequest_v1_items_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ListItemsRequest.ProtoReflect.Descriptor instead.
func (*ListItemsRequest) Descriptor() ([]byte, []int) {
	return file_proto_sidequest_v1_items_proto_rawDescGZIP(), []int{2}
}

func (x *ListItemsRequest) GetPage() int32 {
	if x != nil {
		return x.Page
	}
	return 0
}

func (x *ListItemsRequest) GetLimit() int32 {
	if x != nil {
		return x.Limit
	}
	return 0
}

func (x *ListItemsRequest) GetSort() string {
	if x != nil {
		return x.Sort
	}
	return ""
}

func (x *ListItemsRequest) GetLabels() map[string]string {
	if x != nil {
		return x.Labels
	}
	return nil
}

type ListItemsResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Items         []*Item                `protobuf:"bytes,1,rep,name=items,proto3" json:"items,omitempty"`
	Total         int32                  `protobuf:"varint,2,opt,name=total,proto3" json:"total,omitempty"`
	Page          int32                  `protobuf:"varint,3,opt,name=page,proto3" json:"page,omitempty"`
	Limit         int32                  `protobuf:"varint,4,opt,name=limit,proto3" json:"limit,omitempty"`
	Pages         int32                  `protobuf:"varint,5,opt,name=pages,proto3" json:"pages,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ListItemsResponse) Reset() {
	*x = ListItemsResponse{}
	mi := &file_proto_sidequest_v1_items_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ListItemsResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ListItemsResponse) ProtoMessage() {}

func (x *ListItemsResponse) ProtoReflect() protoreflect.Message {
	mi := &file_proto_sidequest_v1_items_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ListItemsResponse.ProtoReflect.Descriptor instead.
func (*ListItemsResponse) Descriptor() ([]byte, []int) {
	return file_proto_sidequest_v1_items_proto_rawDescGZIP(), []int{3}
}

func (x *ListItemsResponse) GetItems() []*Item {
	if x != nil {
		return x.Items
	}
	return nil
}

func (x *ListItemsResponse) GetTotal() int32 {
	if x != nil {
		return x.Total
	}
	return 0
}

func (x *ListItemsResponse) GetPage() int32 {
	if x != nil {
		return x.Page
	}
	return 0
}

func (x *ListItemsResponse) GetLimit() int32 {
	if x != nil {
		return x.Limit
	}
	return 0
}

func (x *ListItemsResponse) GetPages() int32 {
	if x != nil {
		return x.Pages
	}
	return 0
}

type CreateItemRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Name          string                 `protobuf:"bytes,1,opt,name=name,proto3" json:"name,omitempty"`
	Labels        map[string]string      `protobuf:"bytes,2,rep,name=labels,proto3" json:"labels,omitempty" protobuf_key:"bytes,1,opt,name=key" protobuf_val:"bytes,2,opt,name=value"`
	Data          *structpb.Struct       `protobuf:"bytes,3,opt,name=data,proto3" json:"data,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *CreateItemRequest) Reset() {
	*x = CreateItemRequest{}
	mi := &file_proto_sidequest_v1_items_proto_msgTypes[4]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *CreateItemRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CreateItemRequest) ProtoMessage() {}

func (x *CreateItemRequest) ProtoReflect() protoreflect.Message {
	mi := &file_proto_sidequest_v1_items_proto_msgTypes[4]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CreateItemRequest.ProtoReflect.Descriptor instead.
func (*CreateItemRequest) Descriptor() ([]byte, []int) {
	return file_proto_sidequest_v1_items_proto_rawDescGZIP(), []int{4}
}

func (x *CreateItemRequest) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

func (x *CreateItemRequest) GetLabels() map[string]string {
	if x != nil {
		return x.Labels
	}
	return nil
}

func (x *CreateItemRequest) GetData() *structpb.Struct {
	if x != nil {
		return x.Data
	}
	return nil
}

type UpdateItemRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Id            string                 `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
	Name          string                 `protobuf:"bytes,2,opt,name=name,proto3" json:"name,omitempty"`
	Labels        map[string]string      `protobuf:"bytes,3,rep,name=labels,proto3" json:"labels,omitempty" protobuf_key:"bytes,1,opt,name=key" protobuf_val:"bytes,2,opt,name=value"`
	Data          *structpb.Struct       `protobuf:"bytes,4,opt,name=data,proto3" json:"data,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *UpdateItemRequest) Reset() {
	*x = UpdateItemRequest{}
	mi := &file_proto_sidequest_v1_items_proto_msgTypes[5]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *UpdateItemRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*UpdateItemRequest) ProtoMessage() {}

func (x *UpdateItemRequest) ProtoReflect() protoreflect.Message {
	mi := &file_proto_sidequest_v1_items_proto_msgTypes[5]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use UpdateItemRequest.ProtoReflect.Descriptor instead.
func (*UpdateItemRequest) Descriptor() ([]byte, []int) {
	return file_proto_sidequest_v1_items_proto_rawDescGZIP(), []int{5}
}

func (x *UpdateItemRequest) GetId() string {
	if x != nil {
		return x.Id
	}
	return ""
}

func (x *UpdateItemRequest) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

func (x *UpdateItemRequest) GetLabels() map[string]string {
	if x != nil {
		return x.Labels
	}
	return nil
}

func (x *UpdateItemRequest) GetData() *structpb.Struct {
	if x != nil {
		return x.Data
	}
	return nil
}

type DeleteItemRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Id            string                 `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *DeleteItemRequest) Reset() {
	*x = DeleteItemRequest{}
	mi := &file_proto_sidequest_v1_items_proto_msgTypes[6]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *DeleteItemRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*DeleteItemRequest) ProtoMessage() {}

func (x *DeleteItemRequest) ProtoReflect() protoreflect.Message {
	mi := &file_proto_sidequest_v1_items_proto_msgTypes[6]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use DeleteItemRequest.ProtoReflect.Descriptor instead.
func (*DeleteItemRequest) Descriptor() ([]byte, []int) {
	return file_proto_sidequest_v1_items_proto_rawDescGZIP(), []int{6}
}

func (x *DeleteItemRequest) GetId() string {
	if x != nil {
		return x.Id
	}
	return ""
}

type WatchItemsRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Labels        map[string]string      `protobuf:"bytes,1,rep,name=labels,proto3" json:"labels,omitempty" protobuf_key:"bytes,1,opt,name=key" protobuf_val:"bytes,2,opt,name=value"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *WatchItemsRequest) Reset() {
	*x = WatchItemsRequest{}
	mi := &file_proto_sidequest_v1_items_proto_msgTypes[7]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *WatchItemsRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*WatchItemsRequest) ProtoMessage() {}

func (x *WatchItemsRequest) ProtoReflect() protoreflect.Message {
	mi := &file_proto_sidequest_v1_items_proto_msgTypes[7]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use WatchItemsRequest.ProtoReflect.Descriptor instead.
func (*WatchItemsRequest) Descriptor() ([]byte, []int) {
	return file_proto_sidequest_v1_items_proto_rawDescGZIP(), []int{7}
}

func (x *WatchItemsRequest) GetLabels() map[string]string {
	if x != nil {
		return x.Labels
	}
	return nil
}

type ItemEvent struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Type          EventType              `protobuf:"varint,1,opt,name=type,proto3,enum=sidequest.v1.EventType" json:"type,omitempty"`
	Item          *Item                  `protobuf:"bytes,2,opt,name=item,proto3" json:"item,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ItemEvent) Reset() {
	*x = ItemEvent{}
	mi := &file_proto_sidequest_v1_items_proto_msgTypes[8]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ItemEvent) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ItemEvent) ProtoMessage() {}

func (x *ItemEvent) ProtoReflect() protoreflect.Message {
	mi := &file_proto_sidequest_v1_items_proto_msgTypes[8]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ItemEvent.ProtoReflect.Descriptor instead.
func (*ItemEvent) Descriptor() ([]byte, []int) {
	return file_proto_sidequest_v1_items_proto_rawDescGZIP(), []int{8}
}

func (x *ItemEvent) GetType() EventType {
	if x != nil {
		return x.Type
	}
	return EventType_EVENT_TYPE_UNSPECIFIED
}

func (x *ItemEvent) GetItem() *Item {
	if x != nil {
		return x.Item
	}
	return nil
}

var File_proto_sidequest_v1_items_proto protoreflect.FileDescriptor

const file_proto_sidequest_v1_items_proto_rawDesc = "" +
	"\n" +
	"\x1eproto/sidequest/v1/items.proto\x12\fsidequest.v1\x1a\x1fgoogle/protobuf/timestamp.proto\x1a\x1bgoogle/protobuf/empty.proto\x1a\x1cgoogle/protobuf/struct.proto\"\xda\x02\n" +
	"\x04Item\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\tR\x02id\x12\x12\n" +
	"\x04name\x18\x02 \x01(\tR\x04name\x126\n" +
	"\x06labels\x18\x03 \x03(\v2\x1e.sidequest.v1.Item.LabelsEntryR\x06labels\x12+\n" +
	"\x04data\x18\x04 \x01(\v2\x17.google.protobuf.StructR\x04data\x129\n" +
	"\n" +
	"created_at\x18\x05 \x01(\v2\x1a.google.protobuf.TimestampR\tcreatedAt\x129\n" +
	"\n" +
	"updated_at\x18\x06 \x01(\v2\x1a.google.protobuf.TimestampR\tupdatedAt\x12\x18\n" +
	"\aversion\x18\a \x01(\x05R\aversion\x1a9\n" +
	"\vLabelsEntry\x12\x10\n" +
	"\x03key\x18\x01 \x01(\tR\x03key\x12\x14\n" +
	"\x05value\x18\x02 \x01(\tR\x05value:\x028\x01\" \n" +
	"\x0eGetItemRequest\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\tR\x02id\"\xcf\x01\n" +
	"\x10ListItemsRequest\x12\x12\n" +
	"\x04page\x18\x01 \x01(\x05R\x04page\x12\x14\n" +
	"\x05limit\x18\x02 \x01(\x05R\x05limit\x12\x12\n" +
	"\x04sort\x18\x03 \x01(\tR\x04sort\x12B\n" +
	"\x06labels\x18\x04 \x03(\v2*.sidequest.v1.ListItemsRequest.LabelsEntryR\x06labels\x1a9\n" +
	"\vLabelsEntry\x12\x10\n" +
	"\x03key\x18\x01 \x01(\tR\x03key\x12\x14\n" +
	"\x05value\x18\x02 \x01(\tR\x05value:\x028\x01\"\x93\x01\n" +
	"\x11ListItemsResponse\x12(\n" +
	"\x05items\x18\x01 \x03(\v2\x12.sidequest.v1.ItemR\x05items\x12\x14\n" +
	"\x05total\x18\x02 \x01(\x05R\x05total\x12\x12\n" +
	"\x04page\x18\x03 \x01(\x05R\x04page\x12\x14\n" +
	"\x05limit\x18\x04 \x01(\x05R\x05limit\x12\x14\n" +
	"\x05pages\x18\x05 \x01(\x05R\x05pages\"\xd4\x01\n" +
	"\x11CreateItemRequest\x12\x12\n" +
	"\x04name\x18\x01 \x01(\tR\x04name\x12C\n" +
	"\x06labels\x18\x02 \x03(\v2+.sidequest.v1.CreateItemRequest.LabelsEntryR\x06labels\x12+\n" +
	"\x04data\x18\x03 \x01(\v2\x17.google.protobuf.StructR\x04data\x1a9\n" +
	"\vLabelsEntry\x12\x10\n" +
	"\x03key\x18\x01 \x01(\tR\x03key\x12\x14\n" +
	"\x05value\x18\x02 \x01(\tR\x05value:\x028\x01\"\xe4\x01\n" +
	"\x11UpdateItemRequest\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\tR\x02id\x12\x12\n" +
	"\x04name\x18\x02 \x01(\tR\x04name\x12C\n" +
	"\x06labels\x18\x03 \x03(\v2+.sidequest.v1.UpdateItemRequest.LabelsEntryR\x06labels\x12+\n" +
	"\x04data\x18\x04 \x01(\v2\x17.google.protobuf.StructR\x04data\x1a9\n" +
	"\vLabelsEntry\x12\x10\n" +
	"\x03key\x18\x01 \x01(\tR\x03key\x12\x14\n" +
	"\x05value\x18\x02 \x01(\tR\x05value:\x028\x01\"#\n" +
	"\x11DeleteItemRequest\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\tR\x02id\"\x93\x01\n" +
	"\x11WatchItemsRequest\x12C\n" +
	"\x06labels\x18\x01 \x03(\v2+.sidequest.v1.WatchItemsRequest.LabelsEntryR\x06labels\x1a9\n" +
	"\vLabelsEntry\x12\x10\n" +
	"\x03key\x18\x01 \x01(\tR\x03key\x12\x14\n" +
	"\x05value\x18\x02 \x01(\tR\x05value:\x028\x01\"`\n" +
	"\tItemEvent\x12+\n" +
	"\x04type\x18\x01 \x01(\x0e2\x17.sidequest.v1.EventTypeR\x04type\x12&\n" +
	"\x04item\x18\x02 \x01(\v2\x12.sidequest.v1.ItemR\x04item*o\n" +
	"\tEventType\x12\x1a\n" +
	"\x16EVENT_TYPE_UNSPECIFIED\x10\x00\x12\x16\n" +
	"\x12EVENT_TYPE_CREATED\x10\x01\x12\x16\n" +
	"\x12EVENT_TYPE_UPDATED\x10\x02\x12\x16\n" +
	"\x12EVENT_TYPE_DELETED\x10\x032\xaf\x03\n" +
	"\vItemService\x12;\n" +
	"\aGetItem\x12\x1c.sidequest.v1.GetItemRequest\x1a\x12.sidequest.v1.Item\x12L\n" +
	"\tListItems\x12\x1e.sidequest.v1.ListItemsRequest\x1a\x1f.sidequest.v1.ListItemsResponse\x12A\n" +
	"\n" +
	"CreateItem\x12\x1f.sidequest.v1.CreateItemRequest\x1a\x12.sidequest.v1.Item\x12A\n" +
	"\n" +
	"UpdateItem\x12\x1f.sidequest.v1.UpdateItemRequest\x1a\x12.sidequest.v1.Item\x12E\n" +
	"\n" +
	"DeleteItem\x12\x1f.sidequest.v1.DeleteItemRequest\x1a\x16.google.protobuf.Empty\x12H\n" +
	"\n" +
	"WatchItems\x12\x1f.sidequest.v1.WatchItemsRequest\x1a\x17.sidequest.v1.ItemEvent0\x01BEZCgithub.com/MisterGrinvalds/sidequest/proto/sidequest/v1;sidequestv1b\x06proto3"

var (
	file_proto_sidequest_v1_items_proto_rawDescOnce sync.Once
	file_proto_sidequest_v1_items_proto_rawDescData []byte
)

func file_proto_sidequest_v1_items_proto_rawDescGZIP() []byte {
	file_proto_sidequest_v1_items_proto_rawDescOnce.Do(func() {
		file_proto_sidequest_v1_items_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_proto_sidequest_v1_items_proto_rawDesc), len(file_proto_sidequest_v1_items_proto_rawDesc)))
	})
	return file_proto_sidequest_v1_items_proto_rawDescData
}

var file_proto_sidequest_v1_items_proto_enumTypes = make([]protoimpl.EnumInfo, 1)
var file_proto_sidequest_v1_items_proto_msgTypes = make([]protoimpl.MessageInfo, 14)
var file_proto_sidequest_v1_items_proto_goTypes = []any{
	(EventType)(0),                // 0: sidequest.v1.EventType
	(*Item)(nil),                  // 1: sidequest.v1.Item
	(*GetItemRequest)(nil),        // 2: sidequest.v1.GetItemRequest
	(*ListItemsRequest)(nil),      // 3: sidequest.v1.ListItemsRequest
	(*ListItemsResponse)(nil),     // 4: sidequest.v1.ListItemsResponse
	(*CreateItemRequest)(nil),     // 5: sidequest.v1.CreateItemRequest
	(*UpdateItemRequest)(nil),     // 6: sidequest.v1.UpdateItemRequest
	(*DeleteItemRequest)(nil),     // 7: sidequest.v1.DeleteItemRequest
	(*WatchItemsRequest)(nil),     // 8: sidequest.v1.WatchItemsRequest
	(*ItemEvent)(nil),             // 9: sidequest.v1.ItemEvent
	nil,                           // 10: sidequest.v1.Item.LabelsEntry
	nil,                           // 11: sidequest.v1.ListItemsRequest.LabelsEntry
	nil,                           // 12: sidequest.v1.CreateItemRequest.LabelsEntry
	nil,                           // 13: sidequest.v1.UpdateItemRequest.LabelsEntry
	nil,                           // 14: sidequest.v1.WatchItemsRequest.LabelsEntry
	(*structpb.Struct)(nil),       // 15: google.protobuf.Struct
	(*timestamppb.Timestamp)(nil), // 16: google.protobuf.Timestamp
	(*emptypb.Empty)(nil),         // 17: google.protobuf.Empty
}
var file_proto_sidequest_v1_items_proto_depIdxs = []int32{
	10, // 0: sidequest.v1.Item.labels:type_name -> sidequest.v1.Item.LabelsEntry
	15, // 1: sidequest.v1.Item.data:type_name -> google.protobuf.Struct
	16, // 2: sidequest.v1.Item.created_at:type_name -> google.protobuf.Timestamp
	16, // 3: sidequest.v1.Item.updated_at:type_name -> google.protobuf.Timestamp
	11, // 4: sidequest.v1.ListItemsRequest.labels:type_name -> sidequest.v1.ListItemsRequest.LabelsEntry
	1,  // 5: sidequest.v1.ListItemsResponse.items:type_name -> sidequest.v1.Item
	12, // 6: sidequest.v1.CreateItemRequest.labels:type_name -> sidequest.v1.CreateItemRequest.LabelsEntry
	15, // 7: sidequest.v1.CreateItemRequest.data:type_name -> google.protobuf.Struct
	13, // 8: sidequest.v1.UpdateItemRequest.labels:type_name -> sidequest.v1.UpdateItemRequest.LabelsEntry
	15, // 9: sidequest.v1.UpdateItemRequest.data:type_name -> google.protobuf.Struct
	14, // 10: sidequest.v1.WatchItemsRequest.labels:type_name -> sidequest.v1.WatchItemsRequest.LabelsEntry
	0,  // 11: sidequest.v1.ItemEvent.type:type_name -> sidequest.v1.EventType
	1,  // 12: sidequest.v1.ItemEvent.item:type_name -> sidequest.v1.Item
	2,  // 13: sidequest.v1.ItemService.GetItem:input_type -> sidequest.v1.GetItemRequest
	3,  // 14: sidequest.v1.ItemService.ListItems:input_type -> sidequest.v1.ListItemsRequest
	5,  // 15: sidequest.v1.ItemService.CreateItem:input_type -> sidequest.v1.CreateItemRequest
	6,  // 16: sidequest.v1.ItemService.UpdateItem:input_type -> sidequest.v1.UpdateItemRequest
	7,  // 17: sidequest.v1.ItemService.DeleteItem:input_type -> sidequest.v1.DeleteItemRequest
	8,  // 18: sidequest.v1.ItemService.WatchItems:input_type -> sidequest.v1.WatchItemsRequest
	1,  // 19: sidequest.v1.ItemService.GetItem:output_type -> sidequest.v1.Item
	4,  // 20: sidequest.v1.ItemService.ListItems:output_type -> sidequest.v1.ListItemsResponse
	1,  // 21: sidequest.v1.ItemService.CreateItem:output_type -> sidequest.v1.Item
	1,  // 22: sidequest.v1.ItemService.UpdateItem:output_type -> sidequest.v1.Item
	17, // 23: sidequest.v1.ItemService.DeleteItem:output_type -> google.protobuf.Empty
	9,  // 24: sidequest.v1.ItemService.WatchItems:output_type -> sidequest.v1.ItemEvent
	19, // [19:25] is the sub-list for method output_type
	13, // [13:19] is the sub-list for method input_type
	13, // [13:13] is the sub-list for extension type_name
	13, // [13:13] is the sub-list for extension extendee
	0,  // [0:13] is the sub-list for field type_name
}

func init() { file_proto_sidequest_v1_items_proto_init() }
func file_proto_sidequest_v1_items_proto_init() {
	if File_proto_sidequest_v1_items_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_proto_sidequest_v1_items_proto_rawDesc), len(file_proto_sidequest_v1_items_proto_rawDesc)),
			NumEnums:      1,
			NumMessages:   14,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_proto_sidequest_v1_items_proto_goTypes,
		DependencyIndexes: file_proto_sidequest_v1_items_proto_depIdxs,
		EnumInfos:         file_proto_sidequest_v1_items_proto_enumTypes,
		MessageInfos:      file_proto_sidequest_v1_items_proto_msgTypes,
	}.Build()
	File_proto_sidequest_v1_items_proto = out.File
	file_proto_sidequest_v1_items_proto_goTypes = nil
	file_proto_sidequest_v1_items_proto_depIdxs = nil
}
